name: release-deb

on:
  push:
    tags:
    - '*'

jobs:
  release_build:
      strategy:
        matrix:
          include:
            - distro: melodic
              ubuntu: bionic
              bloom: python-bloom
            - distro: noetic
              ubuntu: focal
              bloom: python3-bloom
      runs-on: ubuntu-latest
      container:
        image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-ros-${{ matrix.distro }}-ros-base-latest
        #options: -u root  # setup-node requires root access
      steps:
      - uses: actions/checkout@v2
        with:
          path: '.'
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install deps
        run: |
          ls
          sudo apt update
          rosdep update
          rosdep install --from-path . --ignore-src --rosdistro ${{ matrix.distro }} -y
          sudo apt install -y ${{ matrix.bloom }} fakeroot dpkg-dev debhelper zip
      - name: Build package
        run: |
          ls
          bloom-release  --version
          bloom-generate rosdebian --os-name ubuntu --os-version ${{ matrix.ubuntu }} --ros-distro ${{ matrix.distro }}
          fakeroot debian/rules binary
          mv ../ros-${{ matrix.distro }}-*.deb .
          zip bloom-${{ matrix.distro }}-release-deb.zip ros-${{ matrix.distro }}-*.deb
          ls
      - name: Upload deb
        uses: actions/upload-artifact@v2
        with:
          name: bloom-release-deb
          path: ros-${{ matrix.distro }}-*.deb
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bloom-${{ matrix.distro }}-release-deb.zip
          asset_name: bloom-${{ matrix.distro }}-release-deb.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "Debian release generated using bloom"
